spring:
  profiles:
    default: dev
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  batch:
    job:
      names: eqLoadReadJob # Only automatically run these jobs (comma separated values)